### PR TITLE
Change suggestion for e2e testing

### PR DESCRIPTION
**Pull request by qnimbus**
Hello roramirez,

You suggested that I create some test cases for the changes I made to the time display in the calendar module; I looked into the 'e2e' test suites that you've created and I tried to make some test suites for the changes I made to the calendar module.

I ran into some issues and while I was trying to figure out how to fix these I made some small changes to your 'e2e' code. I hope you don't mind and are willing to give it a look - all 'e2e' tests except for `dev_console.js` now work in Travis CI, even `vendor_spec.js`. I'm having a hard time trying to figure out why the `dev_console.js` test case is not working locally and on Travis CI. But I'm still looking into it....

I think that the changes I made to `global-setup.js` make it slightly easier to work with and to understand - I hope you agree. I took care to create a new folder ('e2e_new') where my version of the files are so you can easily compare/diff with your own files - I didn't want to overwrite yours.

- Changed `global-setup.js` to allow for easier test creation
- Changed each e2e test suite to work with new `global-setup.js`
- All tests (except for `dev_console.js`) now work with Travis CI
- Added a `setupTimeout` function that will allow for a larger timeout when tests are run under Travis CI

Hope this helps - Thanks for implementing the e2e tests! I think a solid test suite is _very_ important for the MagicMirror project and I intend to contribute not only to the MM code but also write solid tests to assure there are no regressions.

Kind regards,

Bas (QNimbus)

### CODE REVIEW

**Comment by roramirez** [comment]
Nice work @QNimbus !

Please, Just replace with your changes the files into e2e. It's not necessary create a new directory.

I really glad to merge your improvements.

**Review by roramirez — CHANGES_REQUESTED** [review]
Please integrate your changes inside tests/e2e directory.

**Comment by qnimbus** [comment]
@roramirez I made the changes you requested.

By the way, have you made any progress on the `dev_console.js` test case? It does open an Electron browserwindow with the dev console open, but somehow I'm unable to properly access the browserwindow object and test positively for the `isDevToolsOpened` test.

I have the feeling it has something to do with window focus, but I already tried to keep the focus on the main electron window and that didn't help.

**Comment by qnimbus** [comment]
@roramirez The reason I'm pushing my suggested changes to your repo/branch is that it's your code (and contribution) so I felt it is up to you when you agree with my refactoring to send a PR to the main MM repo for these changes. Thanks for the great work!

**Comment by roramirez** [comment]
The `dev_console.js` still give me errors. After a long fight ... I deactivated this test and the tests to gone pass in CI.

I think we must will keep desactived for now,  now is not really neccessary keep active this test.

Good work!

**Review by roramirez — APPROVED** [review]

**Pull request merged**
